name = "smile-bot"
main = "src/index.js"
compatibility_date = "2026-09-01"

[vars]
# Put non-secret configuration here if desired.

[[kv_namespaces]]
binding = "ROLE_KV"
id = "ff22bfaf23c0498c9c8ede1738121135"
preview_id = "REPLACE_WITH_KV_PREVIEW_ID"
