name = "smile-bot"
main = "src/index.js"
compatibility_date = "2026-09-01"

[vars]
# Put non-secret configuration here if desired.

[[kv_namespaces]]
binding = "ROLE_KV"
id = "0f21eaf778a745af8fca347f6abab113"
preview_id = "REPLACE_WITH_KV_PREVIEW_ID"
